config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :tb_redirects, :path => 'redirects'
  end
end

app/models/concerns/tb_redirects/has_redirects.rb
module TbRedirects::HasRedirects
  extend ActiveSupport::Concern

  included do
    has_many :tb_redirects, dependent: :destroy, as: :owner
  end
end

app/models/tb_redirect.rb
class TbRedirect < ActiveRecord::Base
  scope :ordered, -> { order('source desc') }
  scope :search, ->(term) { where('source LIKE ?', "%#{term}%") }

  belongs_to :owner,
    polymorphic: true,
    inverse_of: :tb_redirects,
    optional: true

  validates :source, :destination, :created_by, presence: true
  validates :source, uniqueness: true

  validate :source_not_equals_destination
  after_save :destroy_opposite_redirect
  after_save :schedule_loop_detection

  def self.find_with_uri(uri)
    path = URI(uri).path
    uri_without_params = uri.split('?').first
    find_by(
      arel_table[:source].eq(path)
      .or(arel_table[:source].eq(uri_without_params))
    )
  rescue URI::InvalidURIError => e
    logger.debug e.message
    return nil
  end

  def self.create_smart(params)
    redirect = find_or_initialize_by(source: params.delete(:source))
    redirect.assign_attributes(params)
    redirect.save()
    return redirect
  end

  private

  def source_not_equals_destination
    if source == destination
      errors.add(:destination, 'cannot be the same as the source')
    end
    return true
  end

  def destroy_opposite_redirect
    opposite = TbRedirect.find_by(source: destination,
                                  destination: source)
    opposite.destroy if opposite.present?
    return true
  end

  def schedule_loop_detection
    if TbRedirect.where(destination: source).count > 0
      TbRedirects::DetectRedirectLoopJob.perform_later(self)
    end
    return true
  end

end

app/controllers/admin/tb_redirects_controller.rb
class Admin::TbRedirectsController < Admin::ApplicationController

  belongs_to_app :tb_redirects
  add_breadcrumb 'Redirects', :admin_tb_redirects_path
  before_action :load_tb_redirect, only: [:show, :edit, :update, :destroy]

  def index
    @tb_redirects = TbRedirect.ordered.paginate(page: params[:page])
    @tb_redirects = @tb_redirects.search(params[:search]) if params[:search]
    respond_with @tb_redirects
  end

  def show
    respond_with @tb_redirect
  end

  def new
    @tb_redirect = TbRedirect.new
    respond_with @tb_redirect
  end

  def create
    @tb_redirect = TbRedirect.create_smart(tb_redirect_params.merge(created_by: 'user'))
    flash[:notice] = 'Redirect created successfully' if @tb_redirect.errors.none?
    respond_with @tb_redirect, location: admin_tb_redirects_path
  end

  def edit
    respond_with @tb_redirect
  end

  def update
    if @tb_redirect.update_attributes(tb_redirect_params)
      flash[:notice] = 'Redirect updated successfully'
    end
    respond_with @tb_redirect, location: admin_tb_redirects_path
  end

  def destroy
    flash[:notice] = 'Redirect deleted successfully' if @tb_redirect.destroy
    respond_with @tb_redirect, location: admin_tb_redirects_path
  end

  private

  def load_tb_redirect
    @tb_redirect = TbRedirect.find_by!(id: params[:id])
  end

  def tb_redirect_params
    params.require(:tb_redirect).permit(:source, :destination)
  end

end

app/controllers/concerns/tb_redirects/handle_redirects.rb
module TbRedirects::HandleRedirects
  extend ActiveSupport::Concern

  included do
    rescue_from TbCore::NotFoundError, with: :check_for_applicable_redirect
  end

  def check_for_applicable_redirect(error)
    if redirect = TbRedirect.find_with_uri(request.original_url)
      redirect_to redirect.destination, status: :moved_permanently
    else
      handle_request_error(error)
    end
  end
end

app/helpers/admin/tb_redirects_helper.rb
module Admin::TbRedirectsHelper
  def created_by_for_tb_redirect(created_by)
    if created_by == 'user'
      content_tag :span, created_by.titleize, class: 'label label-info'
    else
      content_tag :span, created_by.titleize, class: 'label label-default'
    end
  end
end

app/views/admin/tb_redirects/_form.html.erb
<%= tb_form_for [:admin, @tb_redirect], :remote => true, :data => {:errors => :inline, :success => admin_tb_redirects_path} do |f| %>
  
  <%= tb_form_errors(f.object, :base) %>

  <%= f.tb_text_field :source %>

  <%= f.tb_text_field :destination %>

  <%= f.tb_save_buttons('Redirect', admin_tb_redirects_path) %>

<% end %>

<script>
  $(document).ready(app.admin.tb_redirects.edit);
</script>

app/views/admin/tb_redirects/edit.html.erb
<%= render 'form' %>

app/views/admin/tb_redirects/index.html.erb
<% content_for :data_controls do %>
  <%= render :partial => '/layouts/admin/search', :locals => {:search_path => admin_tb_redirects_path } %>
  <%= link_to "New Redirect", new_admin_tb_redirect_path, :class => "btn btn-primary", :title => "New Redirect" %>
<% end %>

<% content_for :detail do %>
  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Source</th>
          <th>Destination</th>
          <th>Created By</th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        <% @tb_redirects.each do |tb_redirect| %>
          <tr>
            <td><%= link_to tb_redirect.source, tb_redirect.source, :target => :blank %></td>
            <td><%= link_to tb_redirect.destination, tb_redirect.destination, :target => :blank %></td>
            <td><%= created_by_for_tb_redirect(tb_redirect.created_by) %></td>
            <td class="table-actions">
              <%= link_to 'Details', admin_tb_redirect_path(tb_redirect), :class => 'btn btn-default btn-sm' %>
              <%= link_to 'Edit', edit_admin_tb_redirect_path(tb_redirect), :class => 'btn btn-default btn-sm' %>
              <%= link_to 'Delete', admin_tb_redirect_path(tb_redirect), :method => :delete, :class => 'btn btn-danger btn-sm' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= will_paginate @tb_redirects, :renderer => BootstrapPagination::Rails %>

  <script>
    $(document).ready(app.admin.tb_redirects.index);
  </script>

<% end %>

app/views/admin/tb_redirects/new.html.erb
<%= render 'form' %>

app/views/admin/tb_redirects/show.html.erb
<% content_for :data_controls do %>
  <%= link_to 'Edit', edit_admin_tb_redirect_path(@tb_redirect), :class => 'btn btn-default' %>
  <%= link_to "Back", admin_tb_redirects_path, :class => "btn btn-default" %>
<% end %>

<dl class="dl-horizontal">
  <dt>Owner Type:</dt>
  <dd><%= @tb_redirect.owner_type %></dd>
  <dt>Owner:</dt>
  <dd><%= @tb_redirect.owner_id %></dd>
  <dt>Source:</dt>
  <dd><%= @tb_redirect.source %></dd>
  <dt>Destination:</dt>
  <dd><%= @tb_redirect.destination %></dd>
  <dt>Created By:</dt>
  <dd><%= @tb_redirect.created_by %></dd>
</dl>

<script>
  $(document).ready(app.admin.tb_redirects.show);
</script>